### PR TITLE
Address some DST related issues

### PR DESCRIPTION
**Pull request by julian-jelfs**
So this seems to correct both the double occurrence of 1am and the incorrect placements of events. 

As you can see it is pretty horrible and I think it remains a matter of opinion whether it is actually correct. For my use case, it certainly seems closer to correct. 

I have added a test which is runnable by removing the TZ=Utc flag into jest, but as you suggested, it is difficult to test otherwise. 

I wouldn't blame you at all if you didn't want to merge this!  but I think it's the best I can come up with.

### CODE REVIEW

**Comment by mattlewis92** [comment]
Thanks for this! So sorry that I haven't had the chance to look at it just yet, I'm right in the middle of moving at the moment and pretty strapped for time, I will do my best to get to it in the next week or so 😄

**Comment by julian-jelfs** [comment]
Hey don't worry about it at all! Concentrate on your move, I can cope fine on my fork for now.

**Review by mattlewis92 — APPROVED** [review]
Finally had some time this weekend to test this and it works wonderfully, it's so nice to finally find a fix for this issue. Will get this released in the next couple of hours. Thanks again for your contribution! 😄

**Comment by mattlewis92** [comment]
I just released `0.3.3` of `calendar-utils` and `0.27.18` of `angular-calendar` with this fix. Thanks so much for this, it's come up so many times before and I didn't think there was a way of solving it out the box 🎉

**Pull request merged**
