### PR TITLE
ensure that events are plotted in the correct spot when offset change…

### PR DESCRIPTION
**Pull request by julian-jelfs**
…s during the day of the event

### CODE REVIEW

**Comment by julian-jelfs** [comment]
Actually I think I need to close this PR (temporarily perhaps) because it is not enough. It is related to the issue with the hours array in the end. The root problem here is that on the 27th of October there are 25 hours in the day. Somehow we need to decide how to represent that extra hour in the calendar. Offsetting the event in the way I'm proposing here is only the correct solution if we also remove that extra hour from the hours array. Otherwise we have just pushed the problem elsewhere. 

I will continue to try to find a more complete solution, but in the end it seems that it will have to be an opinionated solution as there doesn't really seem to be an objectively correct approach - so whether I will be able come up with something that can be merged back or not I'm not sure.

**Comment by mattlewis92** [comment]
I had a bit of a think about this over the weekend and I thought of a solution that would probably work quite well. What we can do is look at the UTC offset of the start and end of the day, if it's different then we could use the _next day_ to generate the day view, as that won't have a DST change. Each hour segment would then then need an additional date that we use for formatting (so we wouldn't have the same problem of 1 am being displayed twice). It's hacky but I think it would work pretty well to solve the issue, without having to force you into using UTC mode for the calendar. WDYT?

**Comment by julian-jelfs** [comment]
That's an interesting idea. I guess the first thing to decide is whether we agree that despite the fact that there are actually 25 hours in this day, we think the calendar should still display 24. I personally think that is the right thing and it seems to be what other calendars do. Given that, then I think what you are suggesting seems quite promising. I am actively playing around with it at the moment so I can have a play with that idea tomorrow and see what it throws up.

**Comment by mattlewis92** [comment]
My rule of thumb with these things is to use google calendar as a baseline, and it doesn't display days with DST any differently, so I think it's the expected behaviour for this calendar not to either (I've had several issues opened about it before as well). If you wanted to have a play with it, that would be awesome :smile Testing it might be a bit tricky, as right now all the tests are ran in [UTC](https://github.com/mattlewis92/calendar-utils/blob/master/package.json#L9), I'm not sure if there's a way to dynamically change this value or not during runtime (maybe this can help? https://github.com/capaj/set-tz)

**Pull request closed without merging**
