### PR TITLE
feat(getWeekView): add hourDuration option

### PR DESCRIPTION
**Pull request by martinsware**
Based in issue #1080 (https://github.com/mattlewis92/angular-calendar/issues/1080)

### CODE REVIEW

**Review by mattlewis92 — CHANGES_REQUESTED** [review]
Hey thanks for this, it looks like a great start! I played around with it locally and found a few issues.

1/ Can you make it work with the `hourSegments` option? So you can control how many segments appear in each block: https://mattlewis92.github.io/angular-calendar/#/day-view-hour-split

So if you did `[hourSegments]="2"` and `[segmentDuration]="40"` it would split the block into sections like this:
Screenshot 2020-03-29 at 13 10 59

2/ Can you rename `segmentDuration` -> `hourDuration` (an hour is a container of segments, and we're effectively controlling the hour duration, although that's still kind of confusing)

3/ Events aren't positioned correctly as they don't take this option into account. You can adjust the event height and top here: https://github.com/mattlewis92/calendar-utils/blob/master/src/calendar-utils.ts#L958-L980

**Comment by martinsware** [comment]
@mattlewis92, changes done.

**Comment by mattlewis92** [comment]
Awesome, thanks! I still can't see any changes to make sure events are positioned correctly when this option is checked, can you double check that please? 😄

**Comment by martinsware** [comment]
> Awesome, thanks! I still can't see any changes to make sure events are positioned correctly when this option is checked, can you double check that please?

Hey! Sorry, forgot about that
Events are positioned correctly now. Let me know if you need anything else.

Small question: After changes are approved, could you please update the npm package with the changes? I need those in some other projects.

Awesome project! Thanks for everything <3

**Comment by mattlewis92** [comment]
Awesome, thank you! Will take a look over the next couple days and aim to get a release cut asap 😄 In the mean time could you:
1/ resolve the conflict with master please? 
2/ add a small test for the event positioning with this option set

Thanks! 😄

**Comment by martinsware** [comment]
> Awesome, thank you! Will take a look over the next couple days and aim to get a release cut asap  In the mean time could you:
> 1/ resolve the conflict with master please?
> 2/ add a small test for the event positioning with this option set
> 
> Thanks!

Hi!
Conflicts have been resolved and both repos (angular-calendar and calendar-utils) are correctly dealing with events positions, drag and resize events.

Tests were added as well.

Thanks!

**Comment by mattlewis92** [comment]
Awesome, thank you so much! I will take a proper look this weekend and aim to get a beta release cut with it, but my quick spot check looks good so far! 😄

**Review by mattlewis92 — APPROVED** [review]
LGTM, thanks a lot! 👍

**Pull request merged**
