### PR TITLE
fix: add dayjs support to the moment adapter

### PR DESCRIPTION
**Pull request by ghost**
I Would like to add dayjs integration to Angular Calendar library, based on this issue [Issue 1387](https://github.com/mattlewis92/angular-calendar/issues/1387). As I figured out, the first step to integrate adapter, is to add the adapter itself on this library, to use it in Angular calendar afterwards. so this pull request is dedicated on that task

### CODE REVIEW

**Comment by mattlewis92** [comment]
Hey, thanks for this! I think we can go with a really simple solution to supporting day.js, as the moment adapter allows you to pass in moment itself and doesn't use an import, we can just the same adapter. I think if we change [these 2 methods](https://github.com/mattlewis92/calendar-utils/blob/master/src/date-adapters/moment/index.ts#L112-L118) to 

```
function getHours(date: Date | number): number {
    return moment(date).get('hours');
  }

  function getMinutes(date: Date | number): number {
    return moment(date).get('minutes');
  }
```

then it will work with both moment and dayjs. I put together a [quick demo](https://stackblitz.com/edit/angular-4p97fd?file=demo/module.ts) showing how you can use dayjs with the moment adapter.

We can keep the tests you added to verify that it works with dayjs as well. What do you think?

**Comment by ghost** [comment]
Hi, you're welcome :). Yeah its definitely better approach. Shall I change these 2 method in this PR or you will do it yourself ?

**Comment by mattlewis92** [comment]
> Hi, you're welcome :). Yeah its definitely better approach. Shall I change these 2 method in this PR or you will do it yourself ?

Please could you update them in this PR and I will merge and release 😄

**Comment by ghost** [comment]
Sure with a pleasure :), the  only issue we have is the max method, dayjs needs a plugIn in order to work, so we have 2 option either add it manually in moment adapter (not the best option ) or to mention it in docs before using  dayjs to add   this plugin on the client-side ( i think it is the better one )

**Comment by mattlewis92** [comment]
> or to mention it in docs before using dayjs to add this plugin on the client-side ( i think it is the better one )

Yeah I like this idea 😄 We can put together a demo on the calendar website showing people how to use dayjs, similar to the moment one: https://angular-calendar.com/#/moment

**Review by mattlewis92 — APPROVED** [review]
Solid work, thank you!

**Comment by mattlewis92** [comment]
I just released `calendar-utils@0.8.4` with this fix! Now to get this into the calendar itself:

1/ upgrade calendar-utils package in `angular-calendar` repo
2/ fix the calendars extended date adapter to work with the dayjs api: https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/date-adapters/moment/index.ts
3/ Make a new demo showing people how to use dayjs. You can copy and adapt the [moment one](https://github.com/mattlewis92/angular-calendar/tree/master/projects/demos/app/demo-modules/moment)

Let me know if you need any more info @lukaonik 😄

**Comment by xigolle** [comment]
Actually merging from MomentJs to DayJs and saw you guys are working on using DayJs instead of date-fns in your library. 
Just wondering if this is already possible in the current version of angular-calendar? 
Also not yet found the demo any way to help me out if it is already possible ? @mattlewis92  @lukaonik.

A lot of thanks in advance!

**Comment by mattlewis92** [comment]
> Actually merging from MomentJs to DayJs and saw you guys are working on using DayJs instead of date-fns in your library.
> Just wondering if this is already possible in the current version of angular-calendar?
> Also not yet found the demo any way to help me out if it is already possible ? @mattlewis92 @lukaonik.
> 
> A lot of thanks in advance!

Hey, it's not currently implemented but I would happily accept a PR to angular-calendar to add support 😄 All the instructions are in the comment above

**Comment by xigolle** [comment]
@mattlewis92 Great! Will try to accomplish this next week! :)

**Pull request merged**
